-- MySQL Script generated by MySQL Workbench
-- Mon Sep 12 17:56:32 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema shortnews
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shortnews
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shortnews` DEFAULT CHARACTER SET utf8 ;
USE `shortnews` ;

-- -----------------------------------------------------
-- Table `shortnews`.`newspaper`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shortnews`.`newspaper` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `newspaper_name` VARCHAR(45) NOT NULL,
  `title_color` VARCHAR(45) NOT NULL,
  `paper_logo` VARCHAR(255) NOT NULL,
  `paper_tag_color` VARCHAR(45) NOT NULL,
  `video_tag_image` VARCHAR(255) NOT NULL,
  `status` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortnews`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shortnews`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NOT NULL,
  `status` INT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortnews`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shortnews`.`news` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `post_title` VARCHAR(255) NOT NULL,
  `post_content` TEXT(300) NOT NULL,
  `is_video` INT(1) NOT NULL,
  `created` INT NOT NULL,
  `post_image` VARCHAR(255) NOT NULL,
  `status` INT(1) NOT NULL,
  `newspaper_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `video_link` TEXT(300) NULL,
  `full_link` TEXT(300) NOT NULL,
  PRIMARY KEY (`id`, `newspaper_id`, `category_id`),
  INDEX `fk_news_newspaper_idx` (`newspaper_id` ASC),
  INDEX `fk_news_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_news_newspaper`
    FOREIGN KEY (`newspaper_id`)
    REFERENCES `shortnews`.`newspaper` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_news_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `shortnews`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortnews`.`social_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shortnews`.`social_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `logo` VARCHAR(255) NOT NULL,
  `status` INT(1) NOT NULL DEFAULT 1,
  `video_tag` VARCHAR(255) NOT NULL,
  `color_tag` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortnews`.`fan_page`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shortnews`.`fan_page` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `logo` VARCHAR(255) NOT NULL,
  `status` INT(1) NULL DEFAULT 1,
  `social_info_id` INT NOT NULL,
  PRIMARY KEY (`id`, `social_info_id`),
  INDEX `fk_fan_page_social_info1_idx` (`social_info_id` ASC),
  CONSTRAINT `fk_fan_page_social_info1`
    FOREIGN KEY (`social_info_id`)
    REFERENCES `shortnews`.`social_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortnews`.`social_content_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shortnews`.`social_content_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `status` INT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortnews`.`social_media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shortnews`.`social_media` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` TEXT(500) NOT NULL,
  `post_image_url` TEXT(1000) NULL DEFAULT NULL,
  `is_video` INT(1) NOT NULL DEFAULT 0,
  `created` INT NOT NULL,
  `status` INT(1) NULL DEFAULT 1,
  `fan_page_id` INT NOT NULL,
  `full_link` TEXT(300) NULL,
  `video_link` TEXT(300) NULL,
  `separate_image_tag` VARCHAR(55) NOT NULL DEFAULT '--inshortnews--',
  `social_content_type_id` INT NOT NULL,
  PRIMARY KEY (`id`, `fan_page_id`, `social_content_type_id`),
  INDEX `fk_social_media_fan_page1_idx` (`fan_page_id` ASC),
  INDEX `fk_social_media_social_content_type1_idx` (`social_content_type_id` ASC),
  CONSTRAINT `fk_social_media_fan_page1`
    FOREIGN KEY (`fan_page_id`)
    REFERENCES `shortnews`.`fan_page` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_social_media_social_content_type1`
    FOREIGN KEY (`social_content_type_id`)
    REFERENCES `shortnews`.`social_content_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
